version: 2

models:
  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
          - not_null
      - name: full_date
        tests:
          - unique
          - not_null
      - name: year
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: day
        tests:
          - not_null

  - name: dim_categories
    columns:
      - name: category_id
        tests:
          - unique
          - not_null

  - name: dim_developers
    columns:
      - name: developer_id
        tests:
          - unique
          - not_null

  - name: dim_apps
    columns:
      - name: app_sk
        tests:
          - unique
          - not_null
      - name: app_id
        tests:
          - unique
          - not_null
      - name: category_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_categories')
              field: category_id
      - name: developer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_developers')
              field: developer_id

  - name: dim_apps_scd
    columns:
      - name: app_sk
        tests:
          - unique
          - not_null

  - name: fact_reviews
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      - name: app_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_apps_scd')
              field: app_sk
      - name: review_date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: rating
        tests:
          - not_null