- name: fact_reviews
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      # Testing referential integrity using the Surrogate Key
      - name: app_sk
        tests:
          - relationships:
              to: ref('dim_apps_scd')
              field: app_sk